name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container and run tests
        uses: devcontainers/ci@v0.3
        with:
          # Name the image so it can be reused and cached for future runs
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          # Cache from previous builds to speed things up
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          # Only push on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
          # Run our tests inside the devcontainer
          runCmd: |
            source .venv/bin/activate
            pre-commit run --all-files
            python -m pytest
